name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:    
      - main
    paths:
      - 'version.txt'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ é€™å€‹å·¥ä½œ(job) è¢« [${{ github.event_name }}] äº‹ä»¶(envent)é©…å‹•."
      - run: echo "ğŸ§ é€™å€‹å·¥ä½œ(job) è¢« GitHub æŒæ§åœ¨ [${{ runner.os }}] ä¸­åŸ·è¡Œ!"
      - run: echo "ğŸ” åˆ†æ”¯(branch)åç¨± [${{ github.ref }}], å€‰åº«(repository)åç¨± [${{ github.repository }}]."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ é€™å€‹ [${{ github.repository }}] å€‰åº«(repository) è¢«è¤‡è£½åˆ°å·¥ä½œå€."
      - run: echo "ğŸ–¥ï¸ å·¥ä½œå€å·²æº–å‚™åŸ·è¡Œ å·¥ä½œæµ(workflow)."
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
      - run: echo "ğŸ é€™å€‹å·¥ä½œ(job) ç‹€æ…‹ [${{ job.status }}]."
